intent_responses_1={
    "activate_my_card": "To activate your card, login to internet banking, go to my cards and activate my card or visit any nearby ATM.",
    "apple_pay_or_google_pay": "As of now, our card supports Apple Pay and Google Pay virtual wallets in United States for USD transactions.",
    "age_limit": "The minimum age for opening a checking account is 18 years, a children account is 10 years, and a student checking account is 14 years.",
    "card_arrival": "Your card should arrive within 5-10 business days. If it hasn't arrived within this timeframe, please contact us.",
    "card_linking": "To link your card, go to the 'Cards' section in your app, select 'Link Card' and follow the on-screen instructions.",
    "exchange_rate": "Our exchange rates are updated in real-time based on the forex market. You can check the current rate in the app before making a transaction.",
    "card_payment_wrong_exchange_rate": "If you believe your transaction was processed with the wrong exchange rate, please contact us with the transaction details for review.",
    "extra_charge_on_statement": "If you see an extra charge on your statement, please report it immediately in the app under 'Report a Problem' for the specific transaction.",
    "pending_cash_withdrawal": "If your cash withdrawal is still pending, it should be processed within 24 hours. If it takes longer, please contact us.",
    "fiat_currency_support": "We support transactions in over 20 fiat currencies. Check the app for the full list of supported currencies.",
    "card_delivery_estimate": "Expected delivery time for your card is within 7-14 business days. If you need it sooner, consider applying for expedited shipping.",
    "automatic_top_up": "Enable automatic top-up by linking a bank account and setting a threshold balance in your card settings.",
    "card_not_working": "If your card isn't working, check for visible damage or try it at another terminal. If it still doesn't work, report it as damaged in the app.",
    "exchange_via_app": "Exchange currencies directly in the app. Go to 'Currency Exchange', select currencies and enter the amount you want to exchange.",
    "lost_or_stolen_card": "Report lost or stolen cards immediately in the app under 'Cards' > 'Report Lost/Stolen' or call our 24/7 helpline.",
    "pin_blocked": "If your PIN is blocked, you can unblock it in the app under 'Card Management' or by verifying your identity via a call to our support.",
    "contactless_not_working": "If contactless payments are not working, ensure that NFC is enabled on your device and that your card is contactless-enabled.",
    "top_up_by_bank_transfer_charge": "Top-ups by bank transfer are generally free, but some banks may charge a fee. Check with your bank for their specific fees.",
    "pending_top_up": "Pending top-ups are usually resolved within 1 business day. If it takes longer, please check your bank account or contact support.",
    "cancel_transfer": "To cancel a pending transfer, go to 'Transactions', select the transfer and if it's still cancellable, select 'Cancel Transfer'.",
    "top_up_limits": "Top-up limits vary based on your account type and transaction history. Check the 'Limits' section in the app or website for details specific to your account.",
    "wrong_amount_of_cash_received": "If you've received the wrong amount of cash, please report it immediately through the app or contact our customer service for assistance.",
    "card_payment_fee_charged": "Fees for card payments can vary depending on the type of transaction and where it occurs. Detailed fee information is available in the 'Fees and Charges' section of our app or website.",
    "transfer_not_received_by_recipient": "If the recipient hasn't received the transfer, ensure the details entered are correct. If all details are correct and the issue persists, contact support for further investigation.",
    "supported_cards_and_currencies": "We support major credit and debit cards including Visa, MasterCard, and American Express. Our platform handles multiple currencies; a full list is available in the app.",
    "getting_virtual_card": "You can get a virtual card instantly by navigating to the 'Virtual Card' section in our app and following the steps to activate one.",
    "card_acceptance": "Our cards are accepted worldwide at all merchants that display the Visa, MasterCard, or American Express logos, depending on your card type.",
    "top_up_reverted": "If your top-up has been reverted, check your bank account for any discrepancies and ensure your bank card has sufficient funds. For unresolved issues, please contact our support team.",
    "balance_not_updated_after_cheque_or_cash_deposit": "Balance updates after cheque or cash deposits can take up to 3 business days. If your balance is not updated after this period, please contact us.",
    "card_payment_not_recognised": "If a card payment you made is not recognised, please provide the transaction details through the app or contact customer service for a resolution.",
    "edit_personal_details": "To edit your personal details, go to the 'Profile' or 'Settings' section in our app. Make sure to keep your details up to date to avoid any service disruptions.",
    "why_verify_identity": "Verifying your identity helps protect your account from fraud and ensures compliance with financial regulations. This process is crucial for securing your personal and financial information.",
    "unable_to_verify_identity": "If you're unable to verify your identity, ensure you're submitting the required documents in the correct format and they are clearly legible. Contact support for further assistance.",
    "get_physical_card": "To get a physical card, apply through our app under the 'Physical Card' section and follow the instructions for the application process.",
    "visa_or_mastercard": "We offer both Visa and MasterCard options. Your choice can depend on your specific needs such as international usage, benefits, and personal preference.",
    "topping_up_by_card": "To top up by card, simply add your debit or credit card under the 'Funding Source' section in our app and enter the amount you wish to add to your balance.",
    "disposable_card_limits": "Disposable cards have a maximum usage limit and are designed for secure one-time transactions. Check the 'Card Settings' for specific limits and usage guidelines.",
    "compromised_card": "If you suspect your card has been compromised, immediately freeze it in the app and report it under 'Security Options'. We will assist with issuing a new card and securing your account.",
    "atm_support": "Our cards are supported by most ATMs worldwide. If you encounter any issues at an ATM, ensure the machine accepts cards from the Visa or MasterCard network.",
    "direct_debit_payment_not_recognised": "If a direct debit payment is not recognised, please review your authorized payments list and contact us if the issue persists, so we can investigate further.",
    "passcode_forgotten": "If you've forgotten your passcode, use the 'Forgot Passcode' feature in our app to reset it. You will need to verify your identity to set a new passcode.",
    "declined_cash_withdrawal": "Cash withdrawals can be declined due to insufficient funds, incorrect PIN entry, or limits being exceeded. Check your account status and limits in our app.",
    "pending_card_payment": "Pending card payments should be processed within 24 hours. If your payment status has not updated, please contact customer support for assistance.",
    "lost_or_stolen_phone": "If your phone is lost or stolen, please log into your account on another device and deactivate your lost phone's access immediately. Contact our support for further security measures.",
    "request_refund": "To request a refund, please navigate to the transaction in question via our app and select 'Request Refund'. Provide the necessary details, and we will process your request promptly.",
    "declined_transfer": "Transfers may be declined for reasons such as insufficient funds, incorrect account details, or security concerns. Please verify the details and try again, or contact support for assistance.",
    "Refund_not_showing_up": "If your refund isn't showing up, please allow up to 5 business days for processing. If it still hasn't appeared, contact customer service with the transaction details for further investigation.",
    "declined_card_payment": "Card payments can be declined due to insufficient funds, expired card, or blocked transactions. Please check your account details or contact us for clarification.",
    "pending_transfer": "Pending transfers typically complete within one business day. If your transfer has not completed after this time, please contact support for further assistance.",
    "terminate_account": "To terminate your account, please contact customer support directly. We will guide you through the process and ensure all associated balances are properly handled.",
    "card_swallowed": "If an ATM has swallowed your card, contact the ATM provider immediately using the contact details provided on the machine. We can also assist in reissuing a new card.",
    "transaction_charged_twice": "If a transaction appears to be charged twice, please report it through the app or contact our support team directly to resolve the issue and initiate a refund if applicable.",
    "verify_source_of_funds": "Verifying the source of funds is required for compliance with financial regulations. Please submit the necessary documentation through our app or contact support for guidance on acceptable documents.",
    "transfer_timing": "Transfer times can vary depending on the destination country and bank. Most transfers are completed within 1-3 business days. Real-time transfers may be available for certain destinations.",
    "reverted_card_payment": "If a card payment was reverted, it could be due to a processing error or bank reversal. Please check your account for updates or contact customer support for details.",
    "change_pin": "To change your PIN, access the card settings in our app. For security reasons, you may be required to verify your identity before changing your PIN.",
    "beneficiary_not_allowed": "If a beneficiary is not allowed, it may be due to sanctions or compliance regulations. Please check the provided beneficiary details or contact support for further information.",
    "transfer_fee_charged": "Transfer fees depend on the transaction type and destination. Detailed fee information is available in the 'Fees' section of our app.",
    "receiving_money": "Receiving money is typically instant if sent from the same platform; however, receiving from external banks may take longer depending on the sending bank's processing times.",
    "failed_transfer": "If a transfer has failed, please check for any error messages that indicate what went wrong and correct any details if necessary. Contact support for further assistance.",
    "transfer_into_account": "To transfer money into your account, use the 'Receive' option in our app to generate the necessary details for external transfers or to initiate a request to someone else.",
    "verify_top_up": "To verify a top-up, please check the transaction history in our app. If the top-up does not appear, contact customer support for further assistance.",
    "getting_spare_card": "To order a spare card, go to the 'Cards' section in our app and select the option to order a new card. Follow the prompts to complete your request.",
    "top_up_by_cash_or_cheque": "To top up by cash or cheque, visit our designated bank branches or authorized centers. Ensure you have your account details and valid identification for deposits.",
    "order_physical_card": "You can order a physical card through our app by navigating to 'Order Card' and selecting the type of card you need. Follow the steps to confirm your shipping details.",
    "virtual_card_not_working": "If your virtual card is not working, ensure it has not expired and that you have sufficient funds. If issues persist, regenerate a new virtual card in the app.",
    "wrong_exchange_rate_for_cash_withdrawal": "If you believe a cash withdrawal was processed with the wrong exchange rate, please report this in the app with the transaction details for a review.",
    "get_disposable_virtual_card": "To get a disposable virtual card, navigate to the 'Virtual Cards' section in our app and select 'Create Disposable Card'. Use this card for secure one-time online transactions.",
    "top_up_failed": "If your top-up failed, check for any notifications or error messages indicating the issue. Ensure your payment method has sufficient funds and try again.",
    "balance_not_updated_after_bank_transfer": "If your balance is not updated after a bank transfer, allow up to 3 business days for the transaction to process. If it still isn't updated, contact support.",
    "cash_withdrawal_not_recognised": "If a cash withdrawal is not recognized, immediately report the issue through our app providing details of the ATM used and the transaction date.",
    "exchange_charge": "Exchange charges apply when converting currencies. These are calculated based on the current market rate plus a small margin. Details can be found in the 'Fees' section of our app.",
    "top_up_by_card_charge": "Top-ups by card may incur a small fee depending on the card used and the amount. Check our fee structure in the app under the 'Charges' section.",
    "cash_withdrawal_charge": "A fee may be charged for cash withdrawals depending on the ATM network and location. Refer to the 'Fees and Charges' section in our app for specific rates.",
    "card_about_to_expire": "If your card is about to expire, a new card will automatically be issued to you. Please update your shipping details in our app to ensure timely delivery.",
    "verify_my_identity": "Verifying your identity is essential for account security and compliance. Please follow the instructions in our app to submit the required documents.",
    "country_support": "Our services are available in multiple countries. For a list of supported countries, visit the 'Global Access' section in our app."
}
intent_responses_2 = {
    "card_arrival": "Your card should arrive within 7-10 business days. You can track its status in the 'Cards' section of our app. If your card hasn't arrived after 10 days, please contact our customer support directly through the app.",
    "card_linking": "To link your card, enter the card details in the 'Link Card' section under 'My Cards' tab.",
    "exchange_rate": "You can view the current exchange rates directly in the app by going to the 'Rates' section.",
    "card_payment_wrong_exchange_rate": "If you believe the exchange rate was incorrect, please contact support with the transaction details for assistance.",
    "extra_charge_on_statement": "If you see an extra charge on your statement, please report it through the 'Report an Issue' option in the transaction details.",
    "pending_cash_withdrawal": "Cash withdrawals can take a few minutes to reflect. If it takes longer, please contact support.",
    "fiat_currency_support": "Our card supports multiple fiat currencies. Check the 'Currencies' tab to see all supported currencies ",
    "card_delivery_estimate": "The estimated delivery time for your card is listed in the shipping confirmation email.",
    "automatic_top_up": "You can enable automatic top-up in the 'Top Up' section by setting your preferences and linking a funding source.",
    "card_not_working": "If your card is not working, please ensure it is activated. If problems persist, report the card as damaged.",
    "exchange_via_app": "You can exchange currencies directly through our app by selecting 'Exchange' at the bottom menu.",
    "lost_or_stolen_card": "If your card is lost or stolen, please freeze it immediately from the app and order a replacement.",
    "age_limit": "The minimum age limit to apply for a card is 18 years. Ensure you meet this requirement.",
    "pin_blocked": "If your PIN is blocked, you can unblock it by verifying your identity under 'Security Settings'.",
    "contactless_not_working": "If contactless payments are not working, check that the feature is enabled on your card and that your card is near the reader.",
    "top_up_by_bank_transfer_charge": "Top-ups by bank transfer are free, but some banks may charge a transfer fee.",
    "pending_top_up": "If your top-up is pending, it should be credited within a few hours. Contact support if it takes longer.",
    "cancel_transfer": "To cancel a transfer, go to 'Pending Transfers' and select the transaction you want to cancel.",
    "top_up_limits": "Check the 'Limits' section in the app to view your current top-up limits and how to increase them.",
    "wrong_amount_of_cash_received": "If you received the wrong amount of cash, please report the issue in the app with the ATM location and transaction details.",
    "card_payment_fee_charged": "If you were charged a fee for your card payment, please check the 'Fees' section in our app to ensure the fee aligns with our listed charges.",
    "transfer_not_received_by_recipient": "If the recipient has not received the transfer, check the transfer status in 'Transaction History' and ensure the recipient details are correct.",
    "supported_cards_and_currencies": "Our service supports various cards and multiple currencies; please visit the 'Supported Cards' section for detailed info.",
    "getting_virtual_card": "You can get a virtual card instantly by going to 'My Cards' and selecting 'Issue Virtual Card'.",
    "card_acceptance": "Our cards are accepted worldwide. If you experience any issues, please ensure the card network (Visa, Mastercard) is supported by the merchant.",
    "top_up_reverted": "If your top-up was reverted, please check your bank statement to confirm the transaction was processed. Contact customer support for detailed assistance.",
    "balance_not_updated_after_cheque_or_cash_deposit": "Balance updates after a cheque or cash deposit can take 2-3 business days. If it takes longer, please contact support with the deposit details.",
    "card_payment_not_recognised": "If a card payment is not recognised, please freeze your card immediately and report the transaction through the app.",
    "edit_personal_details": "You can edit your personal details under 'Profile Settings'. Make sure your details are up-to-date to avoid service issues.",
    "why_verify_identity": "Verifying your identity helps us ensure the security of your transactions and comply with financial regulations. Please complete it under 'Security Settings'.",
    "unable_to_verify_identity": "If you're unable to verify your identity, ensure your documents are valid and clearly visible. Contact support for further assistance.",
    "get_physical_card": "You can order a physical card by going to 'My Cards' and selecting 'Order Physical Card'. Follow the instructions provided.",
    "visa_or_mastercard": "Our cards are available either as Visa or Mastercard. You can choose your preference when you order your card.",
    "topping_up_by_card": "Top up your account using a debit or credit card by entering your card details in the 'Top Up' section.",
    "disposable_card_limits": "Disposable cards have a usage limit and cannot be topped up. Check the 'Limits' section for more details.",
    "compromised_card": "If you suspect your card is compromised, freeze it immediately and contact support for a replacement.",
    "atm_support": "Our cards are ATM compatible. If you face issues at an ATM, please ensure the machine is operational and accepts Visa or Mastercard.",
    "direct_debit_payment_not_recognised": "For unrecognised direct debit payments, report the issue through the app with the transaction details for a swift resolution.",
    "passcode_forgotten": "If you've forgotten your passcode, you can reset it in the 'Security Settings' by verifying your identity.",
    "declined_cash_withdrawal": "If your cash withdrawal was declined, check for sufficient funds or if the ATM supports international withdrawals. Contact support if issues persist.",
    "pending_card_payment": "If a card payment is pending, it should clear within a few hours. If not, check your internet connection and retry.",
    "lost_or_stolen_phone": "If your phone is lost or stolen, secure your account by logging in on another device and changing your password immediately.",
    "request_refund": "To request a refund, go to the transaction details and use the 'Request Refund' option. Provide the necessary transaction proof.",
    "declined_transfer": "If your transfer was declined, ensure you have enough funds and the recipient's details are correct. Check the 'Transfers' section for more details.",
    "Refund_not_showing_up": "Refunds can take up to 5-10 business days to process. If you don't see your refund after this period, please contact customer support.",
    "declined_card_payment": "Ensure your card is activated and you have sufficient funds. If your card payment is declined, check the merchant's card acceptance or try a different card.",
    "pending_transfer": "If your transfer is pending, please allow up to 24 hours for processing. Contact support if the transfer status does not update.",
    "terminate_account": "To terminate your account, please go to 'Profile Settings' and select 'Close Account'. Follow the steps provided carefully.",
    "card_swallowed": "If an ATM swallows your card, contact the ATM provider immediately followed by our support to secure your account.",
    "transaction_charged_twice": "If a transaction is charged twice, report both transactions in the app. We'll investigate and initiate a refund if verified.",
    "verify_source_of_funds": "Verifying your source of funds is required for compliance. Please provide the requested documentation through the app.",
    "transfer_timing": "Most transfers are processed instantly, but can take up to a day. For specific timing, check the transaction details.",
    "reverted_card_payment": "If a card payment is reverted, it may be due to a processing error. Please try the transaction again or use a different payment method.",
    "change_pin": "To change your PIN, go to 'Security Settings' and select 'Change PIN'. Follow the prompts to set a new PIN.",
    "beneficiary_not_allowed": "If a beneficiary is not allowed, it could be due to sanctions or a blocked region. Check the 'Help' section for more details.",
    "transfer_fee_charged": "Transfer fees depend on the type of transfer and your account plan. Check 'Fees' for detailed information.",
    "receiving_money": "To receive money, share your account details with the sender or use the 'Request Money' feature in our app.",
    "failed_transfer": "If a transfer fails, check your internet connection, recipient details, and ensure you have sufficient funds.",
    "transfer_into_account": "To transfer money into your account, use the 'Add Money' option and select your preferred method of transfer.",
    "verify_top_up": "After topping up, verify the transaction in your 'Transaction History' to ensure funds are added correctly.",
    "getting_spare_card": "You can get a spare card by ordering through 'My Cards'. Spare cards are useful as backups.",
    "top_up_by_cash_or_cheque": "To top up by cash or cheque, visit a participating bank or send a cheque to the address listed in 'Help'.",
    "order_physical_card": "Order a physical card by selecting 'Order Card' in the app. Choose the card type and follow the instructions.",
    "virtual_card_not_working": "If your virtual card is not working, check if it's activated and has not expired. Contact support for assistance.",
    "wrong_exchange_rate_for_cash_withdrawal": "If the exchange rate for a cash withdrawal was incorrect, please provide transaction details through the app for review.",
    "get_disposable_virtual_card": "Get a disposable virtual card for secure online payments by selecting 'Disposable Card' under 'My Cards'.",
    "top_up_failed": "If a top-up fails, check your payment method details, ensure you have funds and retry the transaction.",
    "balance_not_updated_after_bank_transfer": "If your balance isn't updated after a bank transfer, please ensure the transfer was successful and contact support if the issue persists.",
    "cash_withdrawal_not_recognised": "Report the unrecognised cash withdrawal through the app with the ATM details and transaction time.",
    "exchange_charge": "Exchange charges apply when converting currencies. Check 'Fees' to understand the charges specific to your transaction.",
    "top_up_by_card_charge": "A charge may apply when topping up by card depending on your bank and the card used. See 'Fees' for details.",
    "activate_my_card": "To activate your card, go to 'My Cards', select your card, and press 'Activate Card'. Follow any additional verification steps.",
    "cash_withdrawal_charge": "Cash withdrawal fees depend on ATM locations and the amount withdrawn. Refer to the 'Fees' section for specifics.",
    "card_about_to_expire": "If your card is about to expire, order a replacement via the app to continue using your services without interruption.",
    "apple_pay_or_google_pay": "Add your card to Apple Pay or Google Pay through the respective app by selecting 'Add to Digital Wallet'.",
    "verify_my_identity": "Please verify your identity by uploading the required documents through the 'Verify Identity' section in the app.",
    "country_support": "Our services are supported in multiple countries. Check the 'Supported Countries' list in the app for more details."
}

